### ISSUE TITLE
same vocab size for src and  tgt

### ISSUE THREAD

**Issue by catapan** [andrewpeng02/transformer-translation#3]
First of all, thanks for writing the nice tutorial!

I noticed the vocab sizes used for src embedding and tgt embedding are the same. 
https://github.com/andrewpeng02/transformer-translation/blob/master/model.py#L12-L13

I was wondering if you have any justifications on this design choice. Thanks!

**Comment by andrewpeng02** [comment]
I’m glad you found the tutorial helpful! I set the vocab sizes for src and tgt to be the same mainly for simplicity. At my large vocab size of 10k, this covers 99.7% of the total English words and 98.5% of the total French words in the train dataset. So any difference in the src and tgt vocab sizes would result in a negligible performance gain. 

However, to translate between two languages with vastly different vocab sizes (like English to Chinese), adjusting the src and tgt vocab sizes to different values would certainly help. A potential idea to find these vocab sizes is to get the top occurring tokens that cover x% of the dataset for each language.

**Comment by catapan** [comment]
Many thanks for the explanation! It makes sense to me.
